# Generated by Django 5.2.10 on 2026-02-02 16:59

import django.db.models.deletion
import fernet_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_conversation_conversation_type_and_more'),
        ('couples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_phrases', models.JSONField(default=list, help_text='List of detected trigger phrases with context')),
                ('recurring_topics', models.JSONField(default=list, help_text='List of topic matches with prior sessions')),
                ('escalation_score', models.IntegerField(default=0, help_text='Escalation score 0-10')),
                ('ai_summary', fernet_fields.fields.EncryptedTextField(blank=True, help_text='AI-generated insight text', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight_summary', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insight_summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('trigger_phrase', 'Trigger Phrase'), ('recurring_topic', 'Recurring Topic'), ('escalation', 'Escalation')], max_length=20)),
                ('content', models.TextField(help_text='The detected pattern text, e.g. "넌 항상 늦어"')),
                ('category', models.CharField(blank=True, help_text='Topic category: finance, time, household, communication, family, parenting, etc.', max_length=50, null=True)),
                ('severity', models.IntegerField(default=1, help_text='Severity/frequency score 1-5')),
                ('context_snippet', models.TextField(blank=True, default='', help_text='Surrounding text for context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='chat.conversation')),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patterns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('session_count', models.IntegerField(default=0)),
                ('top_topics', models.JSONField(default=list, help_text='List of {topic, count} dicts')),
                ('trigger_frequency', models.JSONField(default=dict, help_text='{phrase: count} dict')),
                ('trend_text', fernet_fields.fields.EncryptedTextField(blank=True, help_text='AI-generated trend description', null=True)),
                ('escalation_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('worsening', 'Worsening')], default='stable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weekly_summaries',
                'ordering': ['-period_end'],
            },
        ),
    ]
