# Generated by Django 5.2.10 on 2026-02-09 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_conversatio_user_id_e93dff_idx_and_more'),
        ('couples', '0001_initial'),
        ('patterns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pattern',
            index=models.Index(fields=['user', 'pattern_type'], name='patterns_user_id_a52f39_idx'),
        ),
        migrations.AddIndex(
            model_name='pattern',
            index=models.Index(fields=['couple', '-created_at'], name='patterns_couple__11158c_idx'),
        ),
        migrations.AddIndex(
            model_name='pattern',
            index=models.Index(fields=['conversation'], name='patterns_convers_069efb_idx'),
        ),
    ]
