# Generated by Django 5.2.10 on 2026-02-08 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], default='low', max_length=20, verbose_name='위험 수준')),
                ('assessment_data', models.JSONField(default=dict, verbose_name='평가 데이터')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('couple_features_enabled', models.BooleanField(default=True, verbose_name='커플 기능 활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_assessment', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '안전 평가',
                'verbose_name_plural': '안전 평가',
                'db_table': 'safety_assessments',
            },
        ),
    ]
