# Generated by Django 5.2.10 on 2026-02-08 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_saved'),
        ('safety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crisis_type', models.CharField(choices=[('suicide', 'Suicide'), ('violence', 'Violence'), ('emergency', 'Emergency')], max_length=20, verbose_name='위기 유형')),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, verbose_name='심각도')),
                ('matched_keywords', models.JSONField(default=list, verbose_name='감지된 키워드')),
                ('message_content', models.TextField(verbose_name='트리거 메시지')),
                ('response_shown', models.TextField(verbose_name='표시된 응답')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crisis_events', to='chat.conversation', verbose_name='대화')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_events', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '위기 이벤트',
                'verbose_name_plural': '위기 이벤트',
                'db_table': 'crisis_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
