# Generated by Django 5.2.10 on 2026-02-12 00:00

import django.db.models.deletion
import fernet_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_tier', models.CharField(choices=[('critical', 'Critical'), ('threshold', 'Threshold'), ('sufficiency', 'Sufficiency'), ('periodic', 'Periodic')], max_length=20)),
                ('trigger_reason', models.TextField()),
                ('data_period_start', models.DateField()),
                ('data_period_end', models.DateField()),
                ('pattern_analysis', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('emotion_analysis', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('balance_analysis', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('resolution_suggestions', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('ethics_review', models.JSONField(default=dict)),
                ('report_title', models.CharField(max_length=200)),
                ('report_summary', fernet_fields.fields.EncryptedTextField()),
                ('key_insights', models.JSONField(default=list)),
                ('suggested_actions', models.JSONField(default=list)),
                ('recommended_activities', models.JSONField(default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('in_conversation_delivered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insight_reports', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insight_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
