# Generated by Django 5.2.10 on 2026-01-22 17:48

import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisclaimerConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('content_hash', models.CharField(max_length=64)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclaimer_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disclaimer_consents',
                'unique_together': {('user', 'version')},
            },
        ),
    ]
