# Generated by Django 5.2.10 on 2026-01-22 17:51

import django.db.models.deletion
import fernet_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0001_initial'),
        ('couples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('requester_consented', models.BooleanField(default=True)),
                ('requester_consented_at', models.DateTimeField(auto_now_add=True)),
                ('responder_consented', models.BooleanField(null=True)),
                ('responder_consented_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('both_consented', 'Both Consented'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('requester_ip', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('responder_ip', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_consents', to='couples.couple')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests_made', to=settings.AUTH_USER_MODEL)),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recording_consents',
                'ordering': ['-created_at'],
            },
        ),
    ]
