# Generated by Django 5.2.10 on 2026-01-23 14:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_goal', models.CharField(choices=[('prevention', '예방 (건강한 관계 유지)'), ('improvement', '개선 (소통 향상)'), ('crisis', '위기 대응 (갈등 해결)')], help_text='주요 목표', max_length=20)),
                ('focus_areas', models.JSONField(default=list, help_text='집중 영역 (최대 3개)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_goals',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_anxiety', models.IntegerField(help_text='불안 애착 수준 (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('attachment_avoidance', models.IntegerField(help_text='회피 애착 수준 (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('conflict_style', models.CharField(choices=[('avoid', '회피형'), ('confront', '대립형'), ('collaborate', '협력형'), ('compromise', '타협형')], help_text='갈등 대응 스타일', max_length=20)),
                ('communication_frequency', models.CharField(choices=[('daily', '매일'), ('weekly', '매주'), ('rarely', '가끔')], help_text='선호하는 대화 빈도', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
