# Generated by Django 5.2.10 on 2026-02-08 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolDown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_seconds', models.IntegerField(default=600)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooldown_sessions', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooldown_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cooldown_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='cooldown_se_user_id_a03fff_idx')],
            },
        ),
    ]
