# Generated by Django 5.2.11 on 2026-02-11 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('category', models.CharField(choices=[('conversation', '대화'), ('game', '게임'), ('exercise', '운동'), ('date', '데이트')], max_length=50, verbose_name='카테고리')),
                ('estimated_minutes', models.IntegerField(default=15, verbose_name='예상 시간(분)')),
                ('difficulty', models.IntegerField(choices=[(1, '쉬움'), (2, '보통'), (3, '도전')], verbose_name='난이도')),
                ('is_featured', models.BooleanField(default=False, verbose_name='추천')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '활동',
                'verbose_name_plural': '활동',
                'db_table': 'activities',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoupleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('in_progress', '진행중'), ('completed', '완료')], default='pending', max_length=20, verbose_name='상태')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_activities', to='activities.activity', verbose_name='활동')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='couples.couple', verbose_name='커플')),
            ],
            options={
                'verbose_name': '커플 활동',
                'verbose_name_plural': '커플 활동',
                'db_table': 'couple_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
