# Generated by Django 5.2.10 on 2026-02-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('text', 'Text Chat'), ('narration', 'Narration Recording'), ('live', 'Live Recording')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='emotion_indicator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
