# Generated by Django 5.2.10 on 2026-02-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_conversation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
