# Generated by Django 5.2.10 on 2026-02-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedreframing',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedreframing',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
