"""Prompts package for chat AI integration."""

from .system_prompts import (
    TWO_MODE_SYSTEM_PROMPT,
    SAFETY_RESPONSE_TEMPLATE,
    SAFETY_KEYWORDS,
    SUMMARIZATION_PROMPT,
    AI_THINKING_MESSAGES,
)

__all__ = [
    'TWO_MODE_SYSTEM_PROMPT',
    'SAFETY_RESPONSE_TEMPLATE',
    'SAFETY_KEYWORDS',
    'SUMMARIZATION_PROMPT',
    'AI_THINKING_MESSAGES',
]
