# Generated by Django 5.2.11 on 2026-02-11 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, verbose_name='현재 연속')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='최장 연속')),
                ('last_checkin_date', models.DateField(blank=True, null=True, verbose_name='마지막 체크인')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='couples.couple', verbose_name='커플')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '연속 기록',
                'verbose_name_plural': '연속 기록',
                'db_table': 'streaks',
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.IntegerField(choices=[(1, '매우 나쁨'), (2, '나쁨'), (3, '보통'), (4, '좋음'), (5, '매우 좋음')], verbose_name='기분')),
                ('note', models.TextField(blank=True, default='', verbose_name='메모')),
                ('date', models.DateField(verbose_name='날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='couples.couple', verbose_name='커플')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '일일 체크인',
                'verbose_name_plural': '일일 체크인',
                'db_table': 'daily_checkins',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
