# Generated by Django 5.2.11 on 2026-02-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycheckin',
            name='answers',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='상세 답변'),
        ),
    ]
