# Generated by Django 5.2.10 on 2026-02-02 16:34

import django.db.models.deletion
import fernet_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('couples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recording_type', models.CharField(choices=[('narration', 'Narration (single speaker)'), ('live', 'Live (multi-speaker)')], max_length=20)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('full_text', fernet_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/temp/')),
                ('emotion_intensity', models.IntegerField(blank=True, null=True)),
                ('post_action', models.CharField(blank=True, choices=[('reframe', 'Reframe'), ('comfort', 'Comfort'), ('keep', 'Keep')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_recordings', to='chat.conversation')),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_recordings', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio_recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker', models.CharField(max_length=50)),
                ('speaker_label', models.CharField(blank=True, max_length=100, null=True)),
                ('text', fernet_fields.fields.EncryptedTextField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('emotion_intensity', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='audio.audiorecording')),
            ],
            options={
                'db_table': 'transcript_segments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_changed', models.CharField(max_length=20)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_edits', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='audio.transcriptsegment')),
            ],
            options={
                'db_table': 'transcript_edits',
                'ordering': ['-created_at'],
            },
        ),
    ]
