# Generated by Django 5.2.10 on 2026-02-08 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ko', models.TextField(verbose_name='질문 (한국어)')),
                ('category', models.CharField(choices=[('daily', '일상'), ('dreams', '꿈/목표'), ('memories', '추억'), ('gratitude', '감사'), ('future', '미래'), ('deep', '깊은 대화')], max_length=50, verbose_name='카테고리')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Deep')], default=1, verbose_name='난이도')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '일일 프롬프트',
                'verbose_name_plural': '일일 프롬프트',
                'db_table': 'daily_prompts',
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyPromptAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(verbose_name='할당일')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_assignments', to='couples.couple', verbose_name='커플')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='prompts.dailyprompt', verbose_name='프롬프트')),
            ],
            options={
                'verbose_name': '프롬프트 할당',
                'verbose_name_plural': '프롬프트 할당',
                'db_table': 'daily_prompt_assignments',
                'ordering': ['-assigned_date'],
                'unique_together': {('couple', 'assigned_date')},
            },
        ),
        migrations.CreateModel(
            name='PromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(verbose_name='답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='prompts.dailypromptassignment', verbose_name='할당')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_responses', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '프롬프트 답변',
                'verbose_name_plural': '프롬프트 답변',
                'db_table': 'prompt_responses',
                'ordering': ['-created_at'],
                'unique_together': {('assignment', 'user')},
            },
        ),
    ]
