# Generated by Django 5.2.10 on 2026-02-08 13:02

from django.db import migrations


def seed_prompts(apps, schema_editor):
    """Seed initial daily conversation prompts."""
    DailyPrompt = apps.get_model('prompts', 'DailyPrompt')

    SEED_PROMPTS = [
        # 일상
        ("오늘 하루 중 가장 기분 좋았던 순간은?", "daily", 1),
        ("요즘 가장 많이 생각하는 것은?", "daily", 1),
        ("이번 주말에 같이 하고 싶은 것이 있다면?", "daily", 1),
        ("오늘 나에게 고마웠던 것이 있다면?", "daily", 1),
        ("요즘 스트레스 받는 일이 있다면?", "daily", 1),
        ("오늘 점심은 뭐 먹었어? 맛있었어?", "daily", 1),
        ("요즘 빠져있는 것이 있다면?", "daily", 1),
        ("오늘 하루를 한 단어로 표현한다면?", "daily", 1),
        ("최근에 웃었던 일이 있다면?", "daily", 1),
        ("요즘 관심 있는 것이 있다면?", "daily", 1),

        # 꿈/목표
        ("올해 꼭 이루고 싶은 목표가 있다면?", "dreams", 2),
        ("10년 후 우리는 어떤 모습일까?", "dreams", 2),
        ("같이 도전해보고 싶은 것이 있다면?", "dreams", 2),
        ("은퇴 후에 하고 싶은 것은?", "dreams", 2),
        ("버킷리스트에 있는 것 하나 알려줘", "dreams", 2),
        ("요즘 배우고 싶은 것이 있다면?", "dreams", 2),
        ("5년 안에 이루고 싶은 것은?", "dreams", 2),
        ("가장 하고 싶은 일은 무엇이야?", "dreams", 2),
        ("꿈꾸는 삶의 모습이 있다면?", "dreams", 2),
        ("우리가 함께 성장하려면 어떻게 해야 할까?", "dreams", 2),

        # 추억
        ("우리가 처음 만났을 때 첫인상은?", "memories", 1),
        ("함께한 여행 중 가장 좋았던 곳은?", "memories", 1),
        ("우리의 가장 웃긴 에피소드는?", "memories", 1),
        ("상대방이 나를 감동시킨 순간은?", "memories", 2),
        ("우리의 첫 데이트 기억나?", "memories", 1),
        ("가장 기억에 남는 생일 선물은?", "memories", 1),
        ("우리가 함께 극복한 어려움이 있다면?", "memories", 2),
        ("가장 행복했던 순간은?", "memories", 1),
        ("둘이 함께한 가장 특별한 날은?", "memories", 1),
        ("서로에게 배운 것이 있다면?", "memories", 2),

        # 감사
        ("상대방에게 가장 감사한 점은?", "gratitude", 1),
        ("상대방의 가장 좋은 점 3가지는?", "gratitude", 1),
        ("최근에 상대방이 해준 것 중 감사한 것은?", "gratitude", 1),
        ("우리 관계에서 가장 자랑스러운 것은?", "gratitude", 2),
        ("상대방에게 꼭 말해주고 싶은 것이 있다면?", "gratitude", 2),
        ("상대방이 있어서 좋은 점은?", "gratitude", 1),
        ("오늘 상대방에게 고마운 것이 있다면?", "gratitude", 1),
        ("상대방이 나를 더 나은 사람으로 만들어준 점은?", "gratitude", 2),
        ("함께해서 감사한 순간은?", "gratitude", 1),
        ("상대방의 어떤 점이 매력적이야?", "gratitude", 1),

        # 미래
        ("같이 가보고 싶은 여행지가 있다면?", "future", 1),
        ("5년 후 우리의 일상은 어떨까?", "future", 2),
        ("같이 살고 싶은 집은 어떤 모습일까?", "future", 2),
        ("노후에 같이 하고 싶은 취미는?", "future", 2),
        ("아이에 대한 생각이 있다면?", "future", 3),
        ("우리의 미래에서 가장 기대되는 것은?", "future", 2),
        ("10년 후 우리는 무엇을 하고 있을까?", "future", 2),
        ("함께 이루고 싶은 꿈이 있다면?", "future", 2),
        ("미래의 우리에게 해주고 싶은 말은?", "future", 2),
        ("앞으로 같이 만들고 싶은 추억은?", "future", 1),

        # 깊은 대화
        ("나에게 바라는 점이 있다면 솔직하게 말해줘", "deep", 3),
        ("우리 관계에서 개선하고 싶은 점은?", "deep", 3),
        ("가장 두려운 것은 무엇이야?", "deep", 3),
        ("사랑한다는 걸 어떻게 표현하면 좋을까?", "deep", 2),
        ("혼자만의 시간이 필요할 때 어떻게 말하면 좋을까?", "deep", 3),
        ("서로에 대해 아직 모르는 것이 있다면?", "deep", 2),
        ("내가 더 잘할 수 있는 것이 있다면?", "deep", 3),
        ("우리가 더 가까워지려면 어떻게 해야 할까?", "deep", 3),
        ("상대방을 더 이해하기 위해 알고 싶은 것은?", "deep", 2),
        ("우리 관계에서 가장 중요한 것은 무엇일까?", "deep", 3),
    ]

    for text_ko, category, difficulty_level in SEED_PROMPTS:
        DailyPrompt.objects.create(
            text_ko=text_ko,
            category=category,
            difficulty_level=difficulty_level,
            is_active=True
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded prompts."""
    DailyPrompt = apps.get_model('prompts', 'DailyPrompt')
    DailyPrompt.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_prompts, reverse_seed),
    ]
